# encoding: utf-8

if File.exist?(redis_wrapper_lib = File.expand_path(File.join(File.dirname(__FILE__), '..', 'redis_wrapper', 'lib')))
  STDERR.puts("Using redis_wrapper lib at #{redis_wrapper_lib}")
  $: << redis_wrapper_lib
end

desc "Run all tests"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.rspec_opts = '--format documentation'
  t.ruby_opts = "-W1"
end

task :default => :spec

task :environment do
end

FileList['lib/redis_wrapper_rails/rails/tasks.rb'].each { |file| load(file) }