# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "redis_wrapper_rails"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["wakemaster39"]
  s.date = "2012-01-17"
  s.description = "Provides rails specific functionality for redis-wrapper. Display's key and method calls to redis along with overall access times in the controller logs.'"
  s.email = "wakemaster39@gmail.com"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Rakefile",
    "lib/redis_wrapper_rails.rb",
    "lib/redis_wrapper_rails/rails.rb",
    "lib/redis_wrapper_rails/rails/log_subscriber.rb",
    "lib/redis_wrapper_rails/rails/railtie.rb",
    "lib/redis_wrapper_rails/rails/railties/controller_runtime.rb",
    "lib/redis_wrapper_rails/rails/redis_instrumentation.rb",
    "lib/redis_wrapper_rails/rails/tasks.rb"
  ]
  s.homepage = "http://github.com/wakemaster39/redis-wrapper"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Rails specific bindings for redis_wrapper"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

